/*
 * Single source of truth for the esbuild bundle options — consumed by
 * esbuild.config.mjs (dev/production builds) and
 * tests/build-freshness.test.js (verifies committed main.js matches source).
 */
const { builtinModules } = require('module');
const builtins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const banner = `/* ============================================================
 * BOB Workspace — Obsidian plugin (forked from Cadence)
 * THIS FILE IS GENERATED by esbuild from src/ — do not edit by hand.
 * Build: npm run build   (sources: src/ TypeScript, templates/ JSON, vendor/)
 * ============================================================ */`;

function buildOptions(root = __dirname) {
  const path = require('path');
  return {
    banner: { js: banner },
    entryPoints: [path.join(root, 'src', 'main.ts')],
    bundle: true,
    external: [
      'obsidian',
      'electron',
      '@codemirror/autocomplete',
      '@codemirror/collab',
      '@codemirror/commands',
      '@codemirror/language',
      '@codemirror/lint',
      '@codemirror/search',
      '@codemirror/state',
      '@codemirror/view',
      '@lezer/common',
      '@lezer/highlight',
      '@lezer/lr',
      ...builtins,
    ],
    format: 'cjs',
    target: 'es2021',
    sourcemap: false,
    treeShaking: true,
    // Never minify: the committed main.js is reviewed in PRs and by the
    // Obsidian store; keep it readable and diffable.
    minify: false,
  };
}

module.exports = { banner, buildOptions };
