const assert = require('assert');
const fs = require('fs');
const path = require('path');

/*
 * The committed main.js is generated by esbuild from src/ (plus the JSON
 * templates and the vendored XLSX lib). It must always match a fresh build —
 * otherwise the repo ships behavior that no longer corresponds to source.
 * Replaces the old per-bundle staleness checks (scripts/bundle-*.js).
 */

const root = path.join(__dirname, '..');
const { buildOptions } = require(path.join(root, 'esbuild.shared.cjs'));
const committed = fs.readFileSync(path.join(root, 'main.js'), 'utf8');

const tmpOut = path.join(__dirname, '.build');
fs.mkdirSync(tmpOut, { recursive: true });
const freshPath = path.join(tmpOut, 'main.fresh.js');

const esbuild = require('esbuild');
esbuild.buildSync({
  ...buildOptions(root),
  outfile: freshPath,
  logLevel: 'silent',
});

const fresh = fs.readFileSync(freshPath, 'utf8');
assert.ok(
  committed === fresh,
  'main.js is stale — run: npm run build (and commit the result)'
);

console.log('build-freshness.test.js: ok');
