require('./base-filter.test');
require('./bases.test');
require('./dashboard-config.test');
require('./dashboard-state.test');
require('./pinned-surfaces.test');
require('./project-note.test');
require('./template-bundle.test');
require('./template-validate.test');
require('./xlsx-bundle.test');
require('./export-view-filter.test');
require('./canvas.test');
require('./widget-source.test');
require('./workspace-config.test');
require('./plugin-load.test');
require('./build-freshness.test');
console.log('all tests passed');
